apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: fiapx-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::239409137076:role/fiapx-api-app-role # Substitua pelo ARN do seu IAM Role na AWS
