apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: fiapx-api
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    # NodePort allows accessing the service from outside the cluster
    # e.g., http://<your-node-ip>:<node-port>
    # minikube users can run: minikube service gateway-service
    nodePort: 30000
  selector:
    app: gateway
